#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Eventarin.Android.Resource", IsApplication=true)]

namespace Eventarin.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Eventarin.Android.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Eventarin.Android.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Eventarin.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Eventarin.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AjayReddy = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AlexFunkhouser = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BernieCronin = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BertOliva = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BharatKrish = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BlainBarton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BrianJaveline = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CarlosMacias = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Coffee = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int DavidSilverlight = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int DebbieKarcher = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int DianeBetancort = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int EricBerkowitz = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int EvieHernandez = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_menu_about = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_menu_dashboard = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_menu_session = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_menu_speaker = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_menu_team = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon_menu_website = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon_social_facebook = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icon_social_linkedin = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icon_social_twitter = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int JamesOsteen = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int JamesParish = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int JamesStepan = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int JasonCarter = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int JonasStawski = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int KevinLevy = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ManuelPalachuk = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int MarilynRousseau = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int MauricioAngee = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int MirMaheed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int nav_refresh = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int NestorUrquiza = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int NickPietroCarlo = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int NoAvatar = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int NoPerson = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int NormanKatz = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int PhilipSchwartz = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int RichieGoldman = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int RickReguiera = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int roundmask = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int roundmask2 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int RussFustino = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int SayedAli = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int SessionBackground = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int SessionBackground1 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int SilkaGonzalez = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int splash = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int splashITP = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int star_gold45 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int star_grey45 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int SteveEarle = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int tab_schedule_unselected = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int WalterQuesada = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int WilliamValez = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ZacharyWeiner = 2130837562;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public const int Eventarin = 2130903040;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
