#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Eventarin.Android.Resource", IsApplication=true)]

namespace Eventarin.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Eventarin.Android.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Eventarin.Android.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Eventarin.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Eventarin.Android.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int planets_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Coffee = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_menu_about = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_menu_dashboard = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_menu_session = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_menu_speaker = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_menu_team = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_menu_website = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_social_facebook = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_social_linkedin = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_social_twitter = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int nav_refresh = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int NoAvatar = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int NoPerson = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int reload = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int roundmask = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int roundmask2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int SessionBackground = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int SessionBackground1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int splash = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int splash2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int splashITP = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int squaremask2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int star_gold45 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int star_grey45 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SteveEarle = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tab_schedule_unselected = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int TeamAdamHeller = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int TeamCarlosMacias = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int TeamDavidSilverlight = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int TeamJonasStawski = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int TeamMirMaheed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int TeamZacharyWeiner = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public const int Eventarin = 2130903040;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int planet_prompt = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
