#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Eventarin.Android.Resource", IsApplication=true)]

namespace Eventarin.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int check = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int check2x = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Default_568h_2x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int LogoFeatureGraphic = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LogoHighRes = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int LogoPromoGraphic = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int plus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int roundmask = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int slideout = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int slideout2x = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int splash_background = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int checkBox1 = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int editText1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int editText2 = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int editText3 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int listView1 = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int myButton = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int test = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int EvolveSQLite = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
