#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Eventarin.Android.Resource", IsApplication=true)]

namespace Eventarin.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Eventarin.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Eventarin.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int check = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int check2x = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Default_568h_2x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int FloorPlanITPalooza = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LogoFeatureGraphic = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int LogoHighRes = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int LogoPromoGraphic = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pin = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pin_map = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int plus = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int roundmask = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int slideout = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int slideout2x = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int splash = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int splash_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int star_gold = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int star_gold45 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int star_grey45 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tab_about = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int tab_exhibitors = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int tab_favorites = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int tab_maps = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int tab_maps_selected = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tab_maps_unselected = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tab_rss = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int tab_schedule = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int tab_schedule_selected = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int tab_schedule_unselected = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int tab_sessions = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tab_sessions_selected = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tab_sessions_unselected = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_speakers = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_speakers_selected = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_speakers_unselected = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_twitter = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int checkBox1 = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int editText1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int editText2 = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int editText3 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int listView1 = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int myButton = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int test = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int EvolveSQLite = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ITPaloozaSQLite = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int PhinTankSQLite = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
